config/routes.rb
Rails.application.routes.draw do
  resources :fragments do
    get 'learn', on: :member
  end

  get 'welcome/index'
end

app/models/fragment.rb
class Fragment < ActiveRecord::Base
  def body_for_html
    body.gsub("\n", "<br/>")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fragments_controller.rb
class FragmentsController < ApplicationController
  before_action :set_fragment, only: [:show, :edit, :update, :destroy]

  def learn
    @current_line = params[:lines].to_i
    @fragment = Fragment.find(params[:id])
    @total_lines = @fragment.body.lines.count
    @lines = @fragment.body.lines.first(@current_line).join('<br>')
  end

  # GET /fragments
  # GET /fragments.json
  def index
    @fragments = Fragment.all
  end

  # GET /fragments/1
  # GET /fragments/1.json
  def show
  end

  # GET /fragments/new
  def new
    @fragment = Fragment.new
  end

  # GET /fragments/1/edit
  def edit
  end

  # POST /fragments
  # POST /fragments.json
  def create
    @fragment = Fragment.new(fragment_params)

    respond_to do |format|
      if @fragment.save
        format.html { redirect_to @fragment, notice: 'Fragment was successfully created.' }
        format.json { render :show, status: :created, location: @fragment }
      else
        format.html { render :new }
        format.json { render json: @fragment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fragments/1
  # PATCH/PUT /fragments/1.json
  def update
    respond_to do |format|
      if @fragment.update(fragment_params)
        format.html { redirect_to @fragment, notice: 'Fragment was successfully updated.' }
        format.json { render :show, status: :ok, location: @fragment }
      else
        format.html { render :edit }
        format.json { render json: @fragment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fragments/1
  # DELETE /fragments/1.json
  def destroy
    @fragment.destroy
    respond_to do |format|
      format.html { redirect_to fragments_url, notice: 'Fragment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fragment
      @fragment = Fragment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fragment_params
      params.require(:fragment).permit(:title, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fragments_helper.rb
module FragmentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/fragments/_form.html.erb
<%= form_for(@fragment) do |f| %>
  <% if @fragment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fragment.errors.count, "error") %> prohibited this fragment from being saved:</h2>

      <ul>
      <% @fragment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fragments/edit.html.erb
<h1>Editing Fragment</h1>

<%= render 'form' %>

<%= link_to 'Show', @fragment %> |
<%= link_to 'Back', fragments_path %>

app/views/fragments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fragments</h1>

<% @fragments.each do |fragment| %>
  <h2>
    <%= fragment.title %>
  </h2>

  <p>
  <%=raw fragment.body_for_html %>
  <br/>
  <%= link_to 'Learn', learn_fragment_path(fragment) %>
  <%= link_to 'Show', fragment %>
  <%= link_to 'Edit', edit_fragment_path(fragment) %>
  <%= link_to 'Destroy', fragment, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

<%= link_to 'New Fragment', new_fragment_path %>

app/views/fragments/learn.html.erb
<h1><%= link_to @fragment.title, learn_fragment_path(@fragment) %></h1>

<% if @total_lines > @current_line %>
  <%= link_to "Next line", learn_fragment_path(@fragment, lines: @current_line + 1) %>
<% end %>

<p>
  <%=raw @lines %>
</p>

app/views/fragments/new.html.erb
<h1>New Fragment!</h1>

<%= render 'form' %>

<%= link_to 'Back', fragments_path %>

app/views/fragments/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @fragment.title %>
</h2>

<p>
  <%=raw @fragment.body_for_html %>
</p>

<%= link_to 'Edit', edit_fragment_path(@fragment) %> |
<%= link_to 'Back', fragments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Memorizer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Roll dice: <%= rand(6) + 1 %></h1>

<% 5.times do %>
<h3>HeLLO</h3>
<% end %>

<% if Time.now.hour < 12 %>
<h2>Morning</h2>
<% else %>
<h2>Afternoon</h2>
<% end %>